### ISSUE TITLE
`Cannot read property 'length' of undefined` after completing `morgue setup`

### ISSUE THREAD

**Issue by mbreaux** [backtrace-labs/backtrace-morgue#15]
```
Username: mbreaux
E-mail address: mbreaux@backtrace.io
Password: ************

Confirm password: ************

/usr/local/lib/node_modules/backtrace-morgue/node_modules/backtrace-node/lib/index.js:147
    throw err;
    ^

TypeError: Cannot read property 'length' of undefined
    at BPG.get (/usr/local/lib/node_modules/backtrace-morgue/dist/lib/bpg.js:224:35)
    at coronerSetupNext (/usr/local/lib/node_modules/backtrace-morgue/dist/bin/morgue.js:194:19)
    at /usr/local/lib/node_modules/backtrace-morgue/dist/bin/morgue.js:256:12
    at /usr/local/lib/node_modules/backtrace-morgue/node_modules/prompt/lib/prompt.js:336:32
    at /usr/local/lib/node_modules/backtrace-morgue/node_modules/async/lib/async.js:154:25
    at assembler (/usr/local/lib/node_modules/backtrace-morgue/node_modules/prompt/lib/prompt.js:333:9)
    at /usr/local/lib/node_modules/backtrace-morgue/node_modules/prompt/lib/prompt.js:342:32
    at /usr/local/lib/node_modules/backtrace-morgue/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/usr/local/lib/node_modules/backtrace-morgue/node_modules/read/lib/read.js:111:5)
    at emitOne (events.js:96:13)
```

**Comment by mbreaux** [comment]
This isn't fixed yet.  Wrong issue was referenced in the PR.
